server-port=25565
online-mode=false
white-list=false
enforce-whitelist=false
max-players=20
motd=JavaScript Minecraft Workshop
difficulty=peaceful
gamemode=creative
spawn-protection=0
enable-rcon=false
level-seed=
view-distance=10
simulation-distance=10
