#!/bin/bash
set -e

# Copy the config (generated by setup.sh) to the volume. Later changes from
# setup.sh (e.g. a different number of servers) are applied as long as the
# copy on the volume was not edited by hand; otherwise only a warning is shown.
BASE=/bungee-base/config.yml
LIVE=/bungee/config.yml
MARK=/bungee/.config-base.sha256
if [ ! -f "$LIVE" ]; then
    cp "$BASE" "$LIVE" && sha256sum < "$BASE" > "$MARK"
elif ! cmp -s "$BASE" "$LIVE"; then
    if [ -f "$MARK" ] && [ "$(sha256sum < "$LIVE")" = "$(cat "$MARK")" ]; then
        cp "$BASE" "$LIVE" && sha256sum < "$BASE" > "$MARK"
        echo "==> config.yml updated from the image (server list changed by setup.sh)."
    else
        echo "==> WARNING: /bungee/config.yml on the volume was edited by hand and differs"
        echo "==>          from the image — keeping it. Merge bungee/config.yml manually if needed."
    fi
fi

cd /bungee
echo "==> Starting BungeeCord..."
exec java \
    -Xms128M \
    -Xmx${BUNGEE_MEM_MAX:-512M} \
    -jar BungeeCord.jar
